# Generated by Django 3.1.7 on 2021-04-09 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='League Name Here', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2021, help_text='Year in YYYY format, ie 2020', max_length=10)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason')], max_length=20, null=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage')),
                ('team', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='season', chained_model_field='season', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.teamseason')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.player')),
                ('season', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='team__season', chained_model_field='team__season', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.roster')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=datetime.time(19, 0), null=True, verbose_name='Time')),
                ('location', models.CharField(blank=True, help_text='Defaults to home team.', max_length=20, null=True)),
                ('stats_entered', models.BooleanField(default=False, null=True, verbose_name='Stats Entered')),
                ('final_score', models.CharField(blank=True, default='---', max_length=20, null=True)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwayTeam', to='league.teamseason', verbose_name='Visitor')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeTeam', to='league.teamseason', verbose_name='Home')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage')),
            ],
        ),
    ]
