# Generated by Django 3.1.7 on 2021-04-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20210409_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='season',
        ),
    ]
