# Generated by Django 3.1.7 on 2021-04-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_roster_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together={('player', 'season')},
        ),
    ]
