# Generated by Django 3.1.7 on 2021-04-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_auto_20210421_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerseason',
            unique_together=set(),
        ),
    ]
