# Generated by Django 3.1.7 on 2021-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_auto_20210422_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_create_season', 'Can Create New Season Objects'), ('can_create_season_stages', 'Can Create New SeasonStage Objects'), ('can_create_games', 'Can Create New Game Objects'), ('can_create_teams', 'Can Create New Team Objects'), ('league_admin', 'Has league admin permissions')),
            },
        ),
    ]
