# Generated by Django 3.1.7 on 2021-05-20 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20210506_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': (('roster_edit', 'Can edit rosters'), ('roster_delete', 'Can delete rosters'), ('roster_create', 'Can create rosters'))},
        ),
    ]
