# Generated by Django 3.1.7 on 2021-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20210520_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': (('user_roster_edit', 'User can edit rosters'), ('user_roster_delete', 'User can delete rosters'), ('user_roster_create', 'User can create rosters'))},
        ),
    ]
