# Generated by Django 3.1.7 on 2021-05-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20210520_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': (('user_roster_add', 'User can add existing players to rosters'), ('user_roster_delete', 'User can delete rosters'), ('user_roster_remove', 'User can remove players from roster'), ('user_roster_create', 'User can create new rosters'), ('user_roster_create_players', 'User can create new players to add to roster'))},
        ),
    ]
