# Generated by Django 3.1.7 on 2021-05-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_auto_20210520_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='url',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
