# Generated by Django 3.1.7 on 2021-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20210531_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='url',
            field=models.SlugField(default=None, max_length=25, unique=True),
        ),
    ]
