# Generated by Django 3.1.7 on 2021-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_auto_20210610_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_stats_entered',
            field=models.BooleanField(default=False, null=True, verbose_name='Stats Entered'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_stats_entered',
            field=models.BooleanField(default=False, null=True, verbose_name='Stats Entered'),
        ),
    ]
