# Generated by Django 3.1.7 on 2021-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_season_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstage',
            name='featured',
            field=models.BooleanField(default=False, null=True, verbose_name='Featured'),
        ),
    ]
