# Generated by Django 3.1.7 on 2021-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20210722_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='featured',
        ),
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.SlugField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
