# Generated by Django 3.1.7 on 2021-08-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_auto_20210811_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.SlugField(blank=True, max_length=3, null=True),
        ),
    ]
