# Generated by Django 3.1.7 on 2021-09-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_auto_20210811_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstage',
            name='stage_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstage',
            name='stage',
            field=models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason'), ('O', 'Other')], max_length=20, null=True),
        ),
    ]
