# Generated by Django 3.1.7 on 2021-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_auto_20210915_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Denotes whether the stage should be the main showcase for stats, standings etc.', verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='seasonstage',
            name='stage',
            field=models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason'), ('O', 'Other')], help_text='The stage the season is in. Each season can contain multiple stages.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstage',
            name='stage_name',
            field=models.CharField(blank=True, default=None, help_text='Used to denote name of stage. IE, Tournament, Preseason. Recommended when selecting stage as other.', max_length=50, null=True),
        ),
    ]
