# Generated by Django 3.1.7 on 2021-09-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_auto_20210915_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
