# Generated by Django 3.1.7 on 2021-09-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0027_season_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='featured',
        ),
    ]
