# Generated by Django 4.0.1 on 2022-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_remove_season_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(default=2022, help_text='Year in YYYY format, ie 2020', max_length=10),
        ),
    ]
