# Generated by Django 4.0.1 on 2022-03-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_alter_game_options_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['-team__season', 'team__team']},
        ),
    ]
