# Generated by Django 3.1.7 on 2021-06-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_auto_20210531_0628'),
        ('user', '0002_auto_20210601_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league'),
        ),
    ]
