# Generated by Django 3.1.7 on 2021-03-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_season_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='type',
        ),
        migrations.CreateModel(
            name='SeasonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason'), ('Pre', 'Preseason')], default='R', max_length=20, null=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.season')),
            ],
        ),
    ]
