# Generated by Django 3.1.7 on 2021-03-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20210326_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.seasonstage')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.team')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamseason')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.seasonstage')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.roster')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPitchingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHittingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
