# Generated by Django 3.1.7 on 2021-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_game_playerhittinggamestats_teamgamestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstage',
            name='stage',
            field=models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason'), ('Pre', 'Preseason')], max_length=20, null=True),
        ),
    ]
