# Generated by Django 3.1.7 on 2021-04-05 13:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_auto_20210405_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgamestats',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.roster'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='player',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='team_stats__roster', chained_model_field='team', null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.playerseason'),
        ),
    ]
