# Generated by Django 3.1.7 on 2021-04-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_auto_20210405_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgamestats',
            name='roster',
        ),
    ]
