# Generated by Django 3.1.7 on 2021-04-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0041_remove_playerhittinggamestats_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgamestats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamseason'),
        ),
    ]
