# Generated by Django 3.1.7 on 2021-04-07 12:06

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_auto_20210407_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestats',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='season', null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamseason', view_name='chained_filter'),
        ),
    ]
