# Generated by Django 3.1.7 on 2021-04-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0045_auto_20210407_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonstage',
            options={},
        ),
    ]
