# Generated by Django 3.1.7 on 2021-04-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20210407_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgamestats',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.roster'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.playerseason'),
        ),
    ]
