# Generated by Django 3.1.7 on 2021-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0048_auto_20210408_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstage',
            name='stage',
            field=models.CharField(choices=[('R', 'Regular Season'), ('P', 'Postseason')], max_length=20, null=True),
        ),
    ]
