# Generated by Django 3.1.7 on 2021-04-09 11:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0051_auto_20210409_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseason',
            name='season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='team__season', chained_model_field='season', null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.seasonstage'),
        ),
    ]
