# Generated by Django 3.1.7 on 2021-04-09 13:02

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0054_auto_20210409_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseason',
            name='season',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='team__season', chained_model_field='team__season', null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.seasonstage'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.seasonstage')),
                ('team', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='season', chained_model_field='season', null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamseason')),
            ],
        ),
        migrations.AlterField(
            model_name='playerseason',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.roster'),
        ),
    ]
