# Generated by Django 3.1.7 on 2021-04-09 13:52

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('stats', '0055_auto_20210409_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='season',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='team',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='season',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='team',
        ),
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
        migrations.RemoveField(
            model_name='seasonstage',
            name='season',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='team',
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.playerseason'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage'),
        ),
        migrations.AlterField(
            model_name='playerhittingstats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.playerseason'),
        ),
        migrations.AlterField(
            model_name='playerpitchingstats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.playerseason'),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='game',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='season', null=True, on_delete=django.db.models.deletion.CASCADE, to='league.game'),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage'),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.teamseason'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerSeason',
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='SeasonStage',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamSeason',
        ),
    ]
