# Generated by Django 3.1.7 on 2021-06-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0017_auto_20210531_0628'),
        ('stats', '0056_auto_20210409_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestats',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.game'),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
