# Generated by Django 3.1.7 on 2021-06-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0057_auto_20210610_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='fielders_choice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='FC'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='reached_on_error',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ROE'),
        ),
    ]
