# Generated by Django 3.1.7 on 2021-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0059_auto_20210615_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgamestats',
            name='owner',
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='average',
            field=models.CharField(default='---', max_length=10, null=True, verbose_name='AVG'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='on_base_percentage',
            field=models.CharField(default='---', max_length=10, null=True, verbose_name='OBP'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='on_base_plus_slugging',
            field=models.CharField(default='---', help_text='On-Base Plus Slugging\nCombined rate of OBP and SLG.\nOBP+SLG', max_length=10, null=True, verbose_name='OPS'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='slugging_percentage',
            field=models.CharField(default='---', max_length=10, null=True, verbose_name='SLG'),
        ),
    ]
