# Generated by Django 3.1.7 on 2021-06-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_auto_20210621_0647'),
        ('stats', '0060_auto_20210617_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='AVG'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='on_base_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='OBP'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='on_base_plus_slugging',
            field=models.FloatField(blank=True, help_text='On-Base Plus Slugging\nCombined rate of OBP and SLG.\nOBP+SLG', null=True, verbose_name='OPS'),
        ),
        migrations.AlterField(
            model_name='playerhittinggamestats',
            name='slugging_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='SLG'),
        ),
        migrations.CreateModel(
            name='PlayerPitchingGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='AB')),
                ('plate_appearances', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PA')),
                ('hits', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='H')),
                ('runs', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='R')),
                ('strikeouts', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SO')),
                ('walks', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='BB')),
                ('singles', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='1B')),
                ('doubles', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='2B')),
                ('triples', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='3B')),
                ('homeruns', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='HR')),
                ('stolen_bases', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SB')),
                ('caught_stealing', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CS')),
                ('runs_batted_in', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='RBI')),
                ('hit_by_pitch', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='HBP')),
                ('sacrifice_flies', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SF')),
                ('sacrifice_bunts', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SAC')),
                ('average', models.CharField(default='---', max_length=10, null=True, verbose_name='AVG')),
                ('on_base_percentage', models.CharField(default='---', max_length=10, null=True, verbose_name='OBP')),
                ('slugging_percentage', models.CharField(default='---', max_length=10, null=True, verbose_name='SLG')),
                ('on_base_plus_slugging', models.CharField(default='---', help_text='On-Base Plus Slugging\nCombined rate of OBP and SLG.\nOBP+SLG', max_length=10, null=True, verbose_name='OPS')),
                ('reached_on_error', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ROE')),
                ('fielders_choice', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='FC')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.playerseason')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.seasonstage')),
                ('team_stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamgamestats')),
            ],
            options={
                'verbose_name': "Hitter's Game Stats",
                'verbose_name_plural': "Hitter's Game Stats",
            },
        ),
    ]
