# Generated by Django 3.1.7 on 2021-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0061_auto_20210622_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerpitchinggamestats',
            options={},
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='at_bats',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='caught_stealing',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='doubles',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='fielders_choice',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='hit_by_pitch',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='homeruns',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='on_base_percentage',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='on_base_plus_slugging',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='plate_appearances',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='reached_on_error',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='runs_batted_in',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='sacrifice_bunts',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='sacrifice_flies',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='singles',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='slugging_percentage',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='stolen_bases',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='triples',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='walks',
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='complete_games',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='CG'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='earned_runs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ER'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='era',
            field=models.FloatField(blank=True, null=True, verbose_name='ERA'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='games',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='G'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='games_started',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='GS'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='hit_batters',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HB'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='hits_allowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='H'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='homeruns_allowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='HR'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='innings_pitched',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='L'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='runs_allowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='save_ops',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SVO'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='saves',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SV'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='shutouts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='SHO'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='walks_allowed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='BB'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='whip',
            field=models.FloatField(blank=True, null=True, verbose_name='WHIP'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='average',
            field=models.FloatField(blank=True, null=True, verbose_name='AVG'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='strikeouts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='K'),
        ),
    ]
