# Generated by Django 3.1.7 on 2021-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0066_auto_20210708_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='pick_offs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PK'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='runners_caught_stealing',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CS'),
        ),
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='stolen_bases_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SB'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='complete_game',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CG'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='earned_runs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ER'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='game',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='game_started',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='GS'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='hit_batters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='HB'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='hits_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='homeruns_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='HR'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='loss',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='runs_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='R'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='save_op',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SVO'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='shutout',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='SHO'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='strikeouts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='walks_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='BB'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='win',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='W'),
        ),
    ]
