# Generated by Django 3.1.7 on 2021-07-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20210722_0811'),
        ('stats', '0068_playerpitchinggamestats_save_converted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_for', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('runs_against', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('win', models.BooleanField(default=None, null=True)),
                ('loss', models.BooleanField(default=None, null=True)),
                ('tie', models.BooleanField(default=None, null=True)),
                ('linescore', models.CharField(blank=True, default='0-0-0-0-0-0-0-0-0', help_text='Line score formatted with dashes, - to separate innings.', max_length=50, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.game')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.teamseason')),
            ],
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.game')),
            ],
        ),
    ]
