# Generated by Django 3.1.7 on 2021-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0069_gameresults_teamgameresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgameresults',
            name='game',
        ),
        migrations.RemoveField(
            model_name='teamgameresults',
            name='team',
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='linescore',
            field=models.CharField(blank=True, default='0-0-0-0-0-0-0-0-0', help_text='Line score formatted with dashes, - to separate innings.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='loss',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='runs_against',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='runs_for',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='tie',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='win',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='GameResults',
        ),
        migrations.DeleteModel(
            name='TeamGameResults',
        ),
    ]
