# Generated by Django 3.1.7 on 2021-07-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0070_auto_20210727_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameLineScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('second', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('third', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fourth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fifth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sixth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('seventh', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('eighth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ninth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('extras', models.CharField(blank=True, default='None', help_text='Extra innings score, formatted with dashes, - to separate each score. Ex for 3 extra innings, 0-1-1.', max_length=50, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.teamgamestats')),
            ],
        ),
    ]
