# Generated by Django 3.1.7 on 2021-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0071_teamgamelinescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='ground_into_double_play',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='GIDP'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='eighth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='8'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='extras',
            field=models.CharField(blank=True, default='None', help_text='Extra innings score, formatted with dashes, - to separate each score. Ex for 3 extra innings, 0-1-1.', max_length=50, null=True, verbose_name='extras'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='fifth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='first',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='fourth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='4'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='ninth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='second',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='seventh',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='7'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='sixth',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='6'),
        ),
        migrations.AlterField(
            model_name='teamgamelinescore',
            name='third',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='3'),
        ),
    ]
