# Generated by Django 3.1.7 on 2021-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0072_auto_20210809_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='batting_order_position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Order Position'),
        ),
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='intentional_walks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='IBB'),
        ),
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='left_on_base',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='LOB'),
        ),
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='starter',
            field=models.BooleanField(default=True, null=True, verbose_name='Starter'),
        ),
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='substitute',
            field=models.BooleanField(default=False, null=True, verbose_name='Sub'),
        ),
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='two_out_runs_batted_in',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='2-out-RBI'),
        ),
    ]
