# Generated by Django 3.1.7 on 2021-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0073_auto_20210809_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhittinggamestats',
            name='picked_off',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='PO'),
        ),
    ]
