# Generated by Django 3.1.7 on 2021-09-27 12:04

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0074_playerhittinggamestats_picked_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpitchinggamestats',
            name='balk',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Balk'),
        ),
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='innings_pitched',
            field=models.FloatField(blank=True, default=0, help_text='Innings Pitched\nUse: .1 - 1 out\n.2 - 2 outs.', null=True, validators=[stats.validators.validate_innings_pitched], verbose_name='IP'),
        ),
    ]
