# Generated by Django 3.1.7 on 2021-10-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0075_auto_20210927_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='average',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='era',
        ),
        migrations.RemoveField(
            model_name='playerpitchinggamestats',
            name='whip',
        ),
    ]
