# Generated by Django 3.1.7 on 2021-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0076_auto_20211005_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpitchinggamestats',
            name='innings_pitched',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Full Innings Pitched\nFor 1/3, 2/3 innings use outs field.', null=True, verbose_name='IP'),
        ),
    ]
