# Generated by Django 3.1.7 on 2021-10-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0078_playerpitchinggamestats__innings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpitchingstats',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerHittingStats',
        ),
        migrations.DeleteModel(
            name='PlayerPitchingStats',
        ),
    ]
