# Generated by Django 3.1.7 on 2021-10-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0079_auto_20211014_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgamestats',
            name='linescore',
        ),
    ]
