# Generated by Django 3.1.7 on 2021-12-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_remove_season_featured'),
        ('stats', '0081_playerhittingstatschoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhittingstatschoice',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league'),
        ),
    ]
