# Generated by Django 4.0.1 on 2022-01-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0082_playerhittingstatschoice_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerHittingStatsChoice',
        ),
    ]
