# Generated by Django 3.1.7 on 2021-03-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_description',
        ),
    ]
