# Generated by Django 3.1.7 on 2021-03-22 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210322_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
