# Generated by Django 3.1.7 on 2021-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210323_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='baseballplaceholder.png', upload_to='article_images'),
        ),
    ]
