# Generated by Django 3.1.7 on 2021-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210323_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='baseballplaceholder2.png', upload_to='article_images'),
        ),
    ]
