# Generated by Django 3.1.7 on 2021-04-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
