# Generated by Django 3.1.7 on 2021-04-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20210429_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='title',
        ),
    ]
