# Generated by Django 4.0.1 on 2022-01-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_alter_season_year'),
        ('league_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple', models.BooleanField(default=True, verbose_name='Simple')),
                ('advanced', models.BooleanField(default=True, verbose_name='Advanced')),
                ('custom', models.BooleanField(default=True, verbose_name='Custom')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueHittingStatsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.BooleanField(default=True, verbose_name='AB')),
                ('plate_appearances', models.BooleanField(default=True, verbose_name='PA')),
                ('hits', models.BooleanField(default=True, verbose_name='H')),
                ('runs', models.BooleanField(default=True, verbose_name='R')),
                ('strikeouts', models.BooleanField(default=True, verbose_name='SO')),
                ('walks', models.BooleanField(default=True, verbose_name='BB')),
                ('singles', models.BooleanField(default=True, verbose_name='1B')),
                ('doubles', models.BooleanField(default=True, verbose_name='2B')),
                ('triples', models.BooleanField(default=True, verbose_name='3B')),
                ('homeruns', models.BooleanField(default=True, verbose_name='HR')),
                ('stolen_bases', models.BooleanField(default=True, verbose_name='SB')),
                ('caught_stealing', models.BooleanField(default=True, verbose_name='CS')),
                ('runs_batted_in', models.BooleanField(default=True, verbose_name='RBI')),
                ('hit_by_pitch', models.BooleanField(default=True, verbose_name='HBP')),
                ('sacrifice_flies', models.BooleanField(default=True, verbose_name='SF')),
                ('sacrifice_bunts', models.BooleanField(default=True, verbose_name='SAC')),
                ('average', models.BooleanField(default=True, verbose_name='AVG')),
                ('on_base_percentage', models.BooleanField(default=True, verbose_name='OBP')),
                ('slugging_percentage', models.BooleanField(default=True, verbose_name='SLG')),
                ('on_base_plus_slugging', models.BooleanField(default=True, help_text='On-Base Plus Slugging\nCombined rate of OBP and SLG.\nOBP+SLG', verbose_name='OPS')),
                ('reached_on_error', models.BooleanField(default=True, verbose_name='ROE')),
                ('fielders_choice', models.BooleanField(default=True, verbose_name='FC')),
                ('intentional_walks', models.BooleanField(default=True, verbose_name='IBB')),
                ('left_on_base', models.BooleanField(default=True, verbose_name='LOB')),
                ('picked_off', models.BooleanField(default=True, verbose_name='PO')),
                ('ground_into_double_play', models.BooleanField(default=True, verbose_name='GIDP')),
                ('two_out_runs_batted_in', models.BooleanField(default=True, verbose_name='2-out-RBI')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('league_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_admin.leaguechoice')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerHittingStatsChoice',
        ),
    ]
