# Generated by Django 4.0.1 on 2022-01-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_admin', '0003_leaguehittingstatsoptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguehittingstatsoptions',
            name='league_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_admin.leagueoptions'),
        ),
    ]
