# Generated by Django 4.0.1 on 2022-01-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_admin', '0004_leaguehittingstatsoptions_league_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueoptions',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='leagueoptions',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='leagueoptions',
            name='simple',
        ),
        migrations.AddField(
            model_name='leagueoptions',
            name='stat_options',
            field=models.CharField(choices=[('S', 'Simple'), ('ADV', 'Advanced'), ('C', 'Custom')], default='S', max_length=3),
        ),
    ]
