# Generated by Django 4.0.1 on 2022-01-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_alter_season_year'),
        ('league_admin', '0005_remove_leagueoptions_advanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueoptions',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league'),
        ),
    ]
