# Generated by Django 4.0.1 on 2022-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_admin', '0006_leagueoptions_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueoptions',
            name='stat_options',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Advanced', 'Advanced'), ('Custom', 'Custom')], default='Simple', max_length=8),
        ),
    ]
