# Generated by Django 4.0.1 on 2022-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('league', '0029_alter_season_year'),
        ('league_admin', '0007_alter_leagueoptions_stat_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeagueOptions',
            new_name='LeagueHittingOptions',
        ),
    ]
