# Generated by Django 4.0.1 on 2022-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_admin', '0008_rename_leagueoptions_leaguehittingoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguehittingstatsoptions',
            name='ordered_lineup',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
    ]
